### ISSUE TITLE
Please update citc_oci.py to include Tokyo

### ISSUE THREAD

**Issue by tanewill** [clusterinthecloud/ansible#32]
Oracle-Linux-7.6-2019.02.20-0
ap-tokyo-1 = "ocid1.image.oc1.ap-tokyo-1.aaaaaaaairi7u3txkamxlw3kmw3dosbesrlm22vsh7yybhygzafd3awhlr5q"

**Comment by milliams** [comment]
Hi Taylor. Thanks for the update. We're having an internal meeting tomorrow to discuss release management etc so this will wait until after that but it will be committed in the next day or so.

**Comment by christopheredsall** [comment]
Hi Taylor, do you have the OCID for the corresponding GPU image?

**Comment by milliams** [comment]
We now fetch the OCID of the image through the API so this is not longer an issue.
